<a href="https://colab.research.google.com/github/EliyaKaheni/ML-playground/blob/main/ChurnPred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libs

In [119]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from xgboost import XGBClassifier

In [112]:
pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.10/dist-packages (0.10.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.10.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (3.2.0)

In [1]:
pip install pre --q pycaret

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.4/484.4 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.4/153.4 kB 10.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 kB 7.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 12.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 11.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.5/17.5 MB 51.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 65.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 70.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 100.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 14.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.2/185.2 kB 17.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 83.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 12.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 kB 19.6 MB/s eta 0:00:00
  Building wheel for pre (setup.py) ... done
  Building wheel for pyod (setup.py) ... done

In [3]:
from pycaret.classification import *

# Loading model

In [69]:
df = pd.read_csv('IT_customer_churn.csv')

In [70]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [71]:
df.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

# Playing with DataFrame

In [72]:
def WhatsGoingOn(df):
  for par in df.columns:
    print(par, '=>', df[par].unique())

WhatsGoingOn(df)

gender => ['Female' 'Male']
SeniorCitizen => [0 1]
Partner => ['Yes' 'No']
Dependents => ['No' 'Yes']
tenure => [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
PhoneService => ['No' 'Yes']
MultipleLines => ['No phone service' 'No' 'Yes']
InternetService => ['DSL' 'Fiber optic' 'No']
OnlineSecurity => ['No' 'Yes' 'No internet service']
OnlineBackup => ['Yes' 'No' 'No internet service']
DeviceProtection => ['No' 'Yes' 'No internet service']
TechSupport => ['No' 'Yes' 'No internet service']
StreamingTV => ['No' 'Yes' 'No internet service']
StreamingMovies => ['No' 'Yes' 'No internet service']
Contract => ['Month-to-month' 'One year' 'Two year']
PaperlessBilling => ['Yes' 'No']
PaymentMethod => ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges => [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges => ['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']
Churn => ['No' 'Yes']

In [73]:
# Numerication

df.replace({'No phone service':0}, inplace=True)
df.replace({'No internet service':0}, inplace=True)
df.replace({'Female':0, 'Male':1}, inplace=True)
df.replace({'No':0, 'Yes':1}, inplace=True)

In [74]:
# Drop the rows which its TotalCharges is ' '
df = df[df['TotalCharges'] != ' ']
df.reset_index()

,index,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,0,1,0,1,0,0,DSL,0,...,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0
1,1,1,0,0,0,34,1,0,DSL,1,...,1,0,0,0,One year,0,Mailed check,56.95,1889.5,0
2,2,1,0,0,0,2,1,0,DSL,1,...,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1
3,3,1,0,0,0,45,0,0,DSL,1,...,1,1,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,4,0,0,0,0,2,1,0,Fiber optic,0,...,0,0,0,0,Month-to-month,1,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,7038,1,0,1,1,24,1,1,DSL,1,...,1,1,1,1,One year,1,Mailed check,84.80,1990.5,0
7028,7039,0,0,1,1,72,1,1,Fiber optic,0,...,1,0,1,1,One year,1,Credit card (automatic),103.20,7362.9,0
7029,7040,0,0,1,1,11,0,0,DSL,1,...,0,0,0,0,Month-to-month,1,Electronic check,29.60,346.45,0
7030,7041,1,1,1,0,4,1,1,Fiber optic,0,...,0,0,0,0,Month-to-month,1,Mailed check,74.40,306.6,1
7031,7042,1,0,0,0,66,1,0,Fiber optic,1,...,1,1,1,1,Two year,1,Bank transfer (automatic),105.65,6844.5,0

In [75]:
df.TotalCharges = pd.to_numeric(df.TotalCharges)

In [76]:
WhatsGoingOn(df)

gender => [0 1]
SeniorCitizen => [0 1]
Partner => [1 0]
Dependents => [0 1]
tenure => [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
PhoneService => [0 1]
MultipleLines => [0 1]
InternetService => ['DSL' 'Fiber optic' 0]
OnlineSecurity => [0 1]
OnlineBackup => [1 0]
DeviceProtection => [0 1]
TechSupport => [0 1]
StreamingTV => [0 1]
StreamingMovies => [0 1]
Contract => ['Month-to-month' 'One year' 'Two year']
PaperlessBilling => [1 0]
PaymentMethod => ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges => [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges => [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
Churn => [0 1]

In [78]:
# Numerication-2
df['Contract'] = df['Contract'].replace({'Month-to-month':1, 'One year':12, 'Two year':24})
df['InternetService'] = df['InternetService'].replace({'DSL':1, 'Fiber optic':2})

In [80]:
# get-dummies
pd.get_dummies(df, ['PaymentMethod'])

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingMovies,Contract,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,1,0,1,...,0,1,1,29.85,29.85,0,0,0,1,0
1,1,0,0,0,34,1,0,1,1,0,...,0,12,0,56.95,1889.50,0,0,0,0,1
2,1,0,0,0,2,1,0,1,1,1,...,0,1,1,53.85,108.15,1,0,0,0,1
3,1,0,0,0,45,0,0,1,1,0,...,0,12,0,42.30,1840.75,0,1,0,0,0
4,0,0,0,0,2,1,0,2,0,0,...,0,1,1,70.70,151.65,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,1,1,0,...,1,12,1,84.80,1990.50,0,0,0,0,1
7039,0,0,1,1,72,1,1,2,0,1,...,1,12,1,103.20,7362.90,0,0,1,0,0
7040,0,0,1,1,11,0,0,1,1,0,...,0,1,1,29.60,346.45,0,0,0,1,0
7041,1,1,1,0,4,1,1,2,0,0,...,0,1,1,74.40,306.60,1,0,0,0,1
7042,1,0,0,0,66,1,0,2,1,0,...,1,24,1,105.65,6844.50,0,1,0,0,0

In [ ]:
df.dtypes

gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService       int64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract              int64
PaperlessBilling      int64
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

In [81]:
df.dtypes

gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService       int64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract              int64
PaperlessBilling      int64
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

#Ask pycaret to take a look

In [82]:
clf = setup(df, target='Churn')

In [83]:
compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=4542, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

#Splitting the data

In [103]:
X = df.drop(['Churn', 'PaymentMethod'], axis='columns')
Y = df.Churn

In [104]:
x_train, x_test, y_train, y_test = train_test_split(X, Y)

In [105]:
x_train.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,MonthlyCharges,TotalCharges
7018,1,0,1,1,1,1,0,2,0,0,0,0,0,0,1,1,70.65,70.65
4722,0,0,0,0,60,1,0,1,0,1,1,1,1,0,12,1,70.15,4224.70
1460,1,0,0,0,5,1,1,2,0,1,1,0,0,0,1,1,85.30,424.15
5688,1,0,1,1,41,1,0,0,0,0,0,0,0,0,24,1,20.00,879.80
6124,0,0,1,1,57,1,0,1,1,0,1,1,0,0,12,1,59.30,3274.35

In [106]:
x_test.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,MonthlyCharges,TotalCharges
1600,1,1,0,0,1,1,1,2,0,0,1,0,1,0,1,1,88.80,88.80
3563,1,1,0,0,30,1,1,2,1,0,0,0,0,1,1,1,90.50,2595.85
4163,1,0,1,0,65,1,1,1,1,1,1,0,0,0,12,0,67.05,4309.55
3539,1,0,0,0,8,1,0,1,0,0,0,0,0,0,1,1,45.15,438.40
5485,1,0,0,0,1,1,0,1,1,0,0,0,0,0,1,1,50.75,50.75

In [107]:
y_train.value_counts()

0    3855
1    1419
Name: Churn, dtype: int64

In [108]:
y_test.value_counts()

0    1308
1     450
Name: Churn, dtype: int64

# Training the model
Logistic Regression

 RMSE

In [114]:
model1 = LogisticRegression()
model1.fit(x_train, y_train)
y_pred = model1.predict(x_test)
res = classification_report(y_test, y_pred)
print(res)

              precision    recall  f1-score   support

           0       0.85      0.88      0.87      1308
           1       0.62      0.55      0.58       450

    accuracy                           0.80      1758
   macro avg       0.73      0.72      0.72      1758
weighted avg       0.79      0.80      0.79      1758

In [113]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority')
x_sm, y_sm = smote.fit_resample(X, Y)
y_sm.value_counts()

0    5163
1    5163
Name: Churn, dtype: int64

In [116]:
x_train, x_test, y_train, y_test = train_test_split(x_sm, y_sm)
model1.fit(x_train, y_train)
y_pred = model1.predict(x_test)
res = classification_report(y_test, y_pred)
print(res)

              precision    recall  f1-score   support

           0       0.81      0.82      0.81      1254
           1       0.82      0.81      0.82      1328

    accuracy                           0.82      2582
   macro avg       0.82      0.82      0.82      2582
weighted avg       0.82      0.82      0.82      2582

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [117]:
model2 = DecisionTreeClassifier()
model2.fit(x_train, y_train)
y_pred = model2.predict(x_test)
res = classification_report(y_test, y_pred)
print(res)

              precision    recall  f1-score   support

           0       0.79      0.79      0.79      1254
           1       0.80      0.80      0.80      1328

    accuracy                           0.79      2582
   macro avg       0.79      0.79      0.79      2582
weighted avg       0.79      0.79      0.79      2582

In [118]:
model3 = RandomForestClassifier()
model3.fit(x_train, y_train)
y_pred = model3.predict(x_test)
res = classification_report(y_test, y_pred)
print(res)

              precision    recall  f1-score   support

           0       0.83      0.84      0.83      1254
           1       0.85      0.83      0.84      1328

    accuracy                           0.84      2582
   macro avg       0.84      0.84      0.84      2582
weighted avg       0.84      0.84      0.84      2582

In [120]:
model4 = XGBClassifier()
model4.fit(x_train, y_train)
y_pred = model4.predict(x_test)
res = classification_report(y_test, y_pred)
print(res)

              precision    recall  f1-score   support

           0       0.83      0.84      0.84      1254
           1       0.85      0.84      0.84      1328

    accuracy                           0.84      2582
   macro avg       0.84      0.84      0.84      2582
weighted avg       0.84      0.84      0.84      2582

# عشقم XGB <3